/*
 * Replaces the colors in the initial Bootstrap build that needed
 * to be actual color values to work with the modifier functions.
 */
const { readFileSync, writeFileSync } = require('fs')

const filePathInput = './src/static/bootstrap/bootstrap_build.css'
const filePathOutput = './src/static/bootstrap/bootstrap.css'

const bootstrap = readFileSync(filePathInput, 'utf8')

const css = bootstrap
  .replace(/#000;/gi, 'var(--btcpay-color-black);')
  .replace(/#000 !important;/gi, 'var(--btcpay-color-black);')
  .replace(/#fff;/gi, 'var(--btcpay-color-white);')
  .replace(/#fff !important;/gi, 'var(--btcpay-color-white);')

  .replace(/#212529/gi, 'var(--btcpay-color-gray-900)')

  .replace(/#0069d9/gi, 'var(--btcpay-color-primary)')
  .replace(/#00448d/gi, 'var(--btcpay-color-primary-dark)')
  .replace(/#0056b3/gi, 'var(--btcpay-color-primary-dark)')
  .replace(/#0050a6/gi, 'var(--btcpay-color-primary-dark)')
  .replace(/#004a99/gi, 'var(--btcpay-color-primary-dark)')
  .replace(/#003771/gi, 'var(--btcpay-color-primary-dark)')
  .replace(/#001e3e/gi, 'var(--btcpay-color-primary-dark)')
  .replace(/#5aaaff/gi, 'var(--btcpay-color-primary-alpha)')
  .replace(/#8dc4ff/gi, 'var(--btcpay-color-primary-alpha)')
  .replace(/#cce1f7/gi, 'var(--btcpay-color-primary-alpha)')
  .replace(/#b8d5f4/gi, 'var(--btcpay-color-primary-alpha)')
  .replace(/#a2c8f1/gi, 'var(--btcpay-color-primary-alpha)')
  .replace(/rgba\(0, 105, 217, 0\.\d+\)/gi, 'var(--btcpay-color-primary-alpha)')
  .replace(/rgba\(38, 128, 223, 0\.\d+\)/gi, 'var(--btcpay-color-primary-alpha)')

  .replace(/#6c757d/gi, 'var(--btcpay-color-secondary)')
  .replace(/#494f54/gi, 'var(--btcpay-color-secondary-dark)')
  .replace(/#5a6268/gi, 'var(--btcpay-color-secondary-dark)')
  .replace(/#545b62/gi, 'var(--btcpay-color-secondary-dark)')
  .replace(/#4e555b/gi, 'var(--btcpay-color-secondary-dark)')
  .replace(/#383d41/gi, 'var(--btcpay-color-secondary-dark)')
  .replace(/#202326/gi, 'var(--btcpay-color-secondary-dark)')
  .replace(/#e2e3e5/gi, 'var(--btcpay-color-secondary-alpha)')
  .replace(/#d6d8db/gi, 'var(--btcpay-color-secondary-alpha)')
  .replace(/#c8cbcf/gi, 'var(--btcpay-color-secondary-alpha)')
  .replace(/rgba\(130, 138, 145, 0\.\d+\)/gi, 'var(--btcpay-color-secondary-alpha)')
  .replace(/rgba\(108, 117, 125, 0\.\d+\)/gi, 'var(--btcpay-color-secondary-alpha)')

  .replace(/#28a745/gi, 'var(--btcpay-color-success)')
  .replace(/#19692c/gi, 'var(--btcpay-color-success-dark)')
  .replace(/#218838/gi, 'var(--btcpay-color-success-dark)')
  .replace(/#1e7e34/gi, 'var(--btcpay-color-success-dark)')
  .replace(/#1c7430/gi, 'var(--btcpay-color-success-dark)')
  .replace(/#155724/gi, 'var(--btcpay-color-success-dark)')
  .replace(/#0b2e13/gi, 'var(--btcpay-color-success-dark)')
  .replace(/#d4edda/gi, 'var(--btcpay-color-success-alpha)')
  .replace(/#c3e6cb/gi, 'var(--btcpay-color-success-alpha)')
  .replace(/#b1dfbb/gi, 'var(--btcpay-color-success-alpha)')
  .replace(/rgba\(72, 180, 97, 0\.\d+\)/gi, 'var(--btcpay-color-success-alpha)')
  .replace(/rgba\(40, 167, 69, 0\.\d+\)/gi, 'var(--btcpay-color-success-alpha)')

  .replace(/#17a2b8/gi, 'var(--btcpay-color-info)')
  .replace(/#0f6674/gi, 'var(--btcpay-color-info-dark)')
  .replace(/#138496/gi, 'var(--btcpay-color-info-dark)')
  .replace(/#117a8b/gi, 'var(--btcpay-color-info-dark)')
  .replace(/#10707f/gi, 'var(--btcpay-color-info-dark)')
  .replace(/#0c5460/gi, 'var(--btcpay-color-info-dark)')
  .replace(/#062c33/gi, 'var(--btcpay-color-info-dark)')
  .replace(/#d1ecf1/gi, 'var(--btcpay-color-info-alpha)')
  .replace(/#bee5eb/gi, 'var(--btcpay-color-info-alpha)')
  .replace(/#abdde5/gi, 'var(--btcpay-color-info-alpha)')
  .replace(/rgba\(58, 176, 195, 0\.\d+\)/gi, 'var(--btcpay-color-info-alpha)')
  .replace(/rgba\(23, 162, 184, 0\.\d+\)/gi, 'var(--btcpay-color-info-alpha)')

  .replace(/#ffc107/gi, 'var(--btcpay-color-warning)')
  .replace(/#ba8b00/gi, 'var(--btcpay-color-warning-dark)')
  .replace(/#e0a800/gi, 'var(--btcpay-color-warning-dark)')
  .replace(/#d39e00/gi, 'var(--btcpay-color-warning-dark)')
  .replace(/#c69500/gi, 'var(--btcpay-color-warning-dark)')
  .replace(/#856404/gi, 'var(--btcpay-color-warning-dark)')
  .replace(/#533f03/gi, 'var(--btcpay-color-warning-dark)')
  .replace(/#fff3cd/gi, 'var(--btcpay-color-warning-alpha)')
  .replace(/#ffeeba/gi, 'var(--btcpay-color-warning-alpha)')
  .replace(/#ffe8a1/gi, 'var(--btcpay-color-warning-alpha)')
  .replace(/rgba\(222, 170, 12, 0\.\d+\)/gi, 'var(--btcpay-color-warning-alpha)')
  .replace(/rgba\(255, 193, 7, 0\.\d+\)/gi, 'var(--btcpay-color-warning-alpha)')

  .replace(/#dc3545/gi, 'var(--btcpay-color-danger)')
  .replace(/#a71d2a/gi, 'var(--btcpay-color-danger-dark)')
  .replace(/#c82333/gi, 'var(--btcpay-color-danger-dark)')
  .replace(/#bd2130/gi, 'var(--btcpay-color-danger-dark)')
  .replace(/#b21f2d/gi, 'var(--btcpay-color-danger-dark)')
  .replace(/#721c24/gi, 'var(--btcpay-color-danger-dark)')
  .replace(/#491217/gi, 'var(--btcpay-color-danger-dark)')
  .replace(/#f8d7da/gi, 'var(--btcpay-color-danger-alpha)')
  .replace(/#f5c6cb/gi, 'var(--btcpay-color-danger-alpha)')
  .replace(/#f1b0b7/gi, 'var(--btcpay-color-danger-alpha)')
  .replace(/rgba\(225, 83, 97, 0\.\d+\)/gi, 'var(--btcpay-color-danger-alpha)')
  .replace(/rgba\(220, 53, 69, 0\.\d+\)/gi, 'var(--btcpay-color-danger-alpha)')

  .replace(/#f8f9fa/gi, 'var(--btcpay-color-light)')
  .replace(/#cbd3da/gi, 'var(--btcpay-color-light-dark)')
  .replace(/#e2e6ea/gi, 'var(--btcpay-color-light-dark)')
  .replace(/#dae0e5/gi, 'var(--btcpay-color-light-dark)')
  .replace(/#d3d9df/gi, 'var(--btcpay-color-light-dark)')
  .replace(/#818182/gi, 'var(--btcpay-color-light-dark)')
  .replace(/#686868/gi, 'var(--btcpay-color-light-dark)')
  .replace(/#fefefe/gi, 'var(--btcpay-color-light-alpha)')
  .replace(/#fdfdfe/gi, 'var(--btcpay-color-light-alpha)')
  .replace(/#ececf6/gi, 'var(--btcpay-color-light-alpha)')
  .replace(/rgba\(216, 217, 219, 0\.\d+\)/gi, 'var(--btcpay-color-light-alpha)')
  .replace(/rgba\(248, 249, 250, 0\.\d+\)/gi, 'var(--btcpay-color-light-alpha)')

  .replace(/#343a40/gi, 'var(--btcpay-color-dark)')
  .replace(/#121416/gi, 'var(--btcpay-color-dark-dark)')
  .replace(/#23272b/gi, 'var(--btcpay-color-dark-dark)')
  .replace(/#1d2124/gi, 'var(--btcpay-color-dark-dark)')
  .replace(/#171a1d/gi, 'var(--btcpay-color-dark-dark)')
  .replace(/#1b1e21/gi, 'var(--btcpay-color-dark-dark)')
  .replace(/#040505/gi, 'var(--btcpay-color-dark-dark)')
  .replace(/#d6d8d9/gi, 'var(--btcpay-color-dark-alpha)')
  .replace(/#c6c8ca/gi, 'var(--btcpay-color-dark-alpha)')
  .replace(/#b9bbbe/gi, 'var(--btcpay-color-dark-alpha)')
  .replace(/rgba\(82, 88, 93, 0\.\d+\)/gi, 'var(--btcpay-color-dark-alpha)')
  .replace(/rgba\(52, 58, 64, 0\.\d+\)/gi, 'var(--btcpay-color-dark-alpha)')

writeFileSync(filePathOutput, css, 'utf8')
